version: '3.1'
services:
  postgres:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: homebus-development
    networks: 
      - homebus-net

  redis:
    image: redis:7.0.11
    ports:
      - "6379:6379"
    networks: 
      - homebus-net

  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
      - '/app/tmp' # don't mount tmp directory
    networks: 
      - homebus-net
    environment:
      RAILS_ENV: development
      RAILS_DOCKER: 1
      REDIS_URL: redis://redis:6379/0

  mosquitto:
    image: eclipse-mosquitto:2.0.15
    ports:
      - "1883:1883"
    networks: 
      - homebus-net

  web:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: ["bin/rails","server","-b","0.0.0.0","-p","3000"]
    ports:
      - "127.0.0.1:3000:3000"
    links:
      - postgres
      - redis
      - sidekiq
    volumes:
      - .:/app
    environment:
      DOCKER: docker
      RAILS_ENV: development
      RAILS_DOCKER: 1
      REDIS_URL: redis://redis:6379/0
    env_file: .env.docker
    networks: 
      - homebus-net 

networks:
  homebus-net:
