---

dependencies: []

galaxy_info:
  description: "Install Mosquitto."
  license: MIT
  min_ansible_version: 2.2
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic
  categories:
    - development
