---

- name: Converge
  hosts: all

  pre_tasks:
    - name: Install net-tools
      become: yes
      apt:
        name: net-tools
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - role: mosquitto
